# Generated by Django 3.1.1 on 2020-09-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(default='', max_length=100)),
                ('Last_Name', models.CharField(default='', max_length=100)),
                ('Email', models.EmailField(default='', max_length=100)),
                ('Password', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
